import { db } from '@/db';
import { merchants } from '@/db/schema';

async function main() {
    const sampleMerchants = [
        {
            merchantCode: 'AMZ001',
            name: 'Amazon',
            category: 'E-Commerce',
            contactPhone: null,
            description: null,
            totalTransactions: 15420,
            rating: 4.8,
            featured: true,
            logo: '🛒',
            createdAt: new Date().toISOString(),
        },
        {
            merchantCode: 'SWG001',
            name: 'Swiggy',
            category: 'Food Delivery',
            contactPhone: null,
            description: null,
            totalTransactions: 12350,
            rating: 4.6,
            featured: true,
            logo: '🍔',
            createdAt: new Date().toISOString(),
        },
        {
            merchantCode: 'ZOM001',
            name: 'Zomato',
            category: 'Food Delivery',
            contactPhone: null,
            description: null,
            totalTransactions: 11200,
            rating: 4.5,
            featured: true,
            logo: '🍕',
            createdAt: new Date().toISOString(),
        },
        {
            merchantCode: 'FLP001',
            name: 'Flipkart',
            category: 'E-Commerce',
            contactPhone: null,
            description: null,
            totalTransactions: 10800,
            rating: 4.7,
            featured: true,
            logo: '🛍️',
            createdAt: new Date().toISOString(),
        },
        {
            merchantCode: 'NET001',
            name: 'Netflix',
            category: 'Entertainment',
            contactPhone: null,
            description: null,
            totalTransactions: 8500,
            rating: 4.9,
            featured: false,
            logo: '🎬',
            createdAt: new Date().toISOString(),
        },
        {
            merchantCode: 'AIR001',
            name: 'Airtel',
            category: 'Telecom',
            contactPhone: null,
            description: null,
            totalTransactions: 9200,
            rating: 4.4,
            featured: false,
            logo: '📱',
            createdAt: new Date().toISOString(),
        },
        {
            merchantCode: 'JIO001',
            name: 'Jio',
            category: 'Telecom',
            contactPhone: null,
            description: null,
            totalTransactions: 8800,
            rating: 4.3,
            featured: false,
            logo: '📲',
            createdAt: new Date().toISOString(),
        },
        {
            merchantCode: 'MSB001',
            name: 'MSEB',
            category: 'Utilities',
            contactPhone: null,
            description: null,
            totalTransactions: 7500,
            rating: 4.2,
            featured: false,
            logo: '⚡',
            createdAt: new Date().toISOString(),
        },
        {
            merchantCode: 'BMS001',
            name: 'BookMyShow',
            category: 'Entertainment',
            contactPhone: null,
            description: null,
            totalTransactions: 6800,
            rating: 4.6,
            featured: false,
            logo: '🎭',
            createdAt: new Date().toISOString(),
        },
        {
            merchantCode: 'UBR001',
            name: 'Uber',
            category: 'Transportation',
            contactPhone: null,
            description: null,
            totalTransactions: 9500,
            rating: 4.5,
            featured: true,
            logo: '🚗',
            createdAt: new Date().toISOString(),
        },
        {
            merchantCode: 'OLA001',
            name: 'Ola',
            category: 'Transportation',
            contactPhone: null,
            description: null,
            totalTransactions: 8900,
            rating: 4.4,
            featured: false,
            logo: '🚕',
            createdAt: new Date().toISOString(),
        },
        {
            merchantCode: 'DMT001',
            name: "Domino's Pizza",
            category: 'Food & Dining',
            contactPhone: null,
            description: null,
            totalTransactions: 7200,
            rating: 4.3,
            featured: false,
            logo: '🍕',
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(merchants).values(sampleMerchants);
    
    console.log('✅ Merchants seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});