import { db } from '@/db';
import { transactions } from '@/db/schema';

async function main() {
    const now = new Date();
    const oneMinuteAgo = new Date(now.getTime() - 1 * 60 * 1000);
    const threeMinutesAgo = new Date(now.getTime() - 3 * 60 * 1000);
    const fiveMinutesAgo = new Date(now.getTime() - 5 * 60 * 1000);

    const sampleTransactions = [
        // EXISTING 10 TRANSACTIONS (PRESERVED)
        {
            txnRef: 'UPI2025011510300001',
            type: 'P2P',
            fromUserId: '2E3BCE0423',
            toUserId: 'USER002',
            toMerchantId: null,
            recipientName: 'Rahul Kumar',
            amount: -500,
            status: 'SUCCESS',
            channel: 'UPI',
            description: 'Payment to friend',
            createdAt: new Date('2025-01-15T10:30:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025011509150002',
            type: 'PAYMENT',
            fromUserId: '2E3BCE0423',
            toUserId: null,
            toMerchantId: 2,
            recipientName: 'Amazon',
            amount: -1299,
            status: 'SUCCESS',
            channel: 'UPI',
            description: 'Online shopping',
            createdAt: new Date('2025-01-15T09:15:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025011418450003',
            type: 'TOPUP',
            fromUserId: null,
            toUserId: '2E3BCE0423',
            toMerchantId: null,
            recipientName: 'P SHASHANK',
            amount: 5000,
            status: 'SUCCESS',
            channel: 'BANK',
            description: 'Bank transfer',
            createdAt: new Date('2025-01-14T18:45:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025011414200004',
            type: 'BILL',
            fromUserId: '2E3BCE0423',
            toUserId: null,
            toMerchantId: 5,
            recipientName: 'MSEB',
            amount: -850,
            status: 'SUCCESS',
            channel: 'UPI',
            description: 'Electricity bill payment',
            createdAt: new Date('2025-01-14T14:20:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025011316100005',
            type: 'P2P',
            fromUserId: 'USER003',
            toUserId: '2E3BCE0423',
            toMerchantId: null,
            recipientName: 'Priya Sharma',
            amount: 250,
            status: 'SUCCESS',
            channel: 'UPI',
            description: 'Payment received',
            createdAt: new Date('2025-01-13T16:10:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025011212350006',
            type: 'PAYMENT',
            fromUserId: '2E3BCE0423',
            toUserId: null,
            toMerchantId: 1,
            recipientName: 'Swiggy',
            amount: -450,
            status: 'SUCCESS',
            channel: 'WALLET',
            description: 'Food delivery',
            createdAt: new Date('2025-01-12T12:35:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025011110200007',
            type: 'PAYMENT',
            fromUserId: '2E3BCE0423',
            toUserId: null,
            toMerchantId: 6,
            recipientName: 'Netflix',
            amount: -649,
            status: 'SUCCESS',
            channel: 'UPI',
            description: 'Subscription renewal',
            createdAt: new Date('2025-01-11T10:20:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025011008150008',
            type: 'P2P',
            fromUserId: '2E3BCE0423',
            toUserId: 'USER004',
            toMerchantId: null,
            recipientName: 'Amit Patel',
            amount: -1000,
            status: 'FAILED',
            channel: 'UPI',
            description: 'Payment failed',
            createdAt: new Date('2025-01-10T08:15:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025010915300009',
            type: 'BILL',
            fromUserId: '2E3BCE0423',
            toUserId: null,
            toMerchantId: 7,
            recipientName: 'Airtel',
            amount: -299,
            status: 'SUCCESS',
            channel: 'UPI',
            description: 'Mobile recharge',
            createdAt: new Date('2025-01-09T15:30:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025010814200010',
            type: 'P2P',
            fromUserId: 'USER002',
            toUserId: '2E3BCE0423',
            toMerchantId: null,
            recipientName: 'Rahul Kumar',
            amount: 500,
            status: 'REFUNDED',
            channel: 'UPI',
            description: 'Refund received',
            createdAt: new Date('2025-01-08T14:20:00.000Z').toISOString(),
        },
        // NEW 5 FAILED TRANSACTIONS
        {
            txnRef: 'UPI2025011517450011',
            type: 'P2P',
            fromUserId: '2E3BCE0423',
            toUserId: 'USER003',
            toMerchantId: null,
            recipientName: 'Priya Sharma',
            amount: -2500,
            status: 'FAILED',
            channel: 'UPI',
            description: 'Insufficient balance',
            createdAt: new Date('2025-01-15T17:45:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025011516200012',
            type: 'PAYMENT',
            fromUserId: '2E3BCE0423',
            toUserId: null,
            toMerchantId: 4,
            recipientName: 'Flipkart',
            amount: -3499,
            status: 'FAILED',
            channel: 'WALLET',
            description: 'Merchant temporarily unavailable',
            createdAt: new Date('2025-01-15T16:20:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025011515100013',
            type: 'BILL',
            fromUserId: '2E3BCE0423',
            toUserId: null,
            toMerchantId: 7,
            recipientName: 'Jio',
            amount: -399,
            status: 'FAILED',
            channel: 'UPI',
            description: 'Network timeout',
            createdAt: new Date('2025-01-15T15:10:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025011513450014',
            type: 'P2P',
            fromUserId: 'USER002',
            toUserId: '2E3BCE0423',
            toMerchantId: null,
            recipientName: 'P SHASHANK',
            amount: 1500,
            status: 'FAILED',
            channel: 'BANK',
            description: 'Bank server error',
            createdAt: new Date('2025-01-15T13:45:00.000Z').toISOString(),
        },
        {
            txnRef: 'UPI2025011512300015',
            type: 'PAYMENT',
            fromUserId: '2E3BCE0423',
            toUserId: null,
            toMerchantId: 10,
            recipientName: 'Uber',
            amount: -285,
            status: 'FAILED',
            channel: 'UPI',
            description: 'Transaction declined by bank',
            createdAt: new Date('2025-01-15T12:30:00.000Z').toISOString(),
        },
        // NEW 3 PENDING TRANSACTIONS
        {
            txnRef: `UPI${Date.now()}001`,
            type: 'P2P',
            fromUserId: '2E3BCE0423',
            toUserId: 'USER004',
            toMerchantId: null,
            recipientName: 'Amit Patel',
            amount: -750,
            status: 'INITIATED',
            channel: 'UPI',
            description: 'Pending payment',
            createdAt: oneMinuteAgo.toISOString(),
        },
        {
            txnRef: `UPI${Date.now()}002`,
            type: 'TOPUP',
            fromUserId: null,
            toUserId: '2E3BCE0423',
            toMerchantId: null,
            recipientName: 'P SHASHANK',
            amount: 3000,
            status: 'INITIATED',
            channel: 'BANK',
            description: 'Bank transfer in progress',
            createdAt: threeMinutesAgo.toISOString(),
        },
        {
            txnRef: `UPI${Date.now()}003`,
            type: 'PAYMENT',
            fromUserId: '2E3BCE0423',
            toUserId: null,
            toMerchantId: 3,
            recipientName: 'Zomato',
            amount: -680,
            status: 'INITIATED',
            channel: 'WALLET',
            description: 'Processing order payment',
            createdAt: fiveMinutesAgo.toISOString(),
        },
    ];

    await db.insert(transactions).values(sampleTransactions);
    
    console.log('✅ Transactions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});